# Generated by Django 4.2.6 on 2024-01-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_remove_schedule_finished_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='order_number',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
