# Generated by Django 4.2.6 on 2024-01-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_remove_schedule_order_number_alter_schedule_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeconfig',
            name='time',
        ),
        migrations.AddField(
            model_name='timeconfig',
            name='time1',
            field=models.CharField(default='9:30-10:50', max_length=15),
        ),
        migrations.AddField(
            model_name='timeconfig',
            name='time2',
            field=models.CharField(default='11:00-12:20', max_length=15),
        ),
        migrations.AddField(
            model_name='timeconfig',
            name='time3',
            field=models.CharField(default='12:30-13:50', max_length=15),
        ),
        migrations.AddField(
            model_name='timeconfig',
            name='time4',
            field=models.CharField(default='14:20-15:40', max_length=15),
        ),
        migrations.AddField(
            model_name='timeconfig',
            name='time5',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='timeconfig',
            name='time6',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='timeconfig',
            name='time7',
            field=models.CharField(default='', max_length=15),
        ),
    ]
