# Generated by Django 4.2.6 on 2024-01-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_remove_timeconfig_time_timeconfig_time1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='daykind',
            field=models.ForeignKey(help_text="Fanni har hafta, toq, juft, bo'sh qoldirish. id ", on_delete=django.db.models.deletion.CASCADE, to='schedules.daykind'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.ForeignKey(help_text='Hafta kunlari POST qilish uchun id sini yuborish kerak', on_delete=django.db.models.deletion.CASCADE, to='schedules.weekday'),
        ),
    ]
