# Generated by Django 4.2.6 on 2024-01-15 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_sending_time'),
        ('schedules', '0007_schedule_is_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeconfig',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
