# Generated by Django 4.2.6 on 2024-02-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_alter_timeconfig_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_empty',
        ),
    ]
