# Generated by Django 4.2.6 on 2024-02-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_remove_schedule_is_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='lesson_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
