# Generated by Django 4.2.6 on 2024-02-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_alter_schedule_lesson_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
