# Generated by Django 4.2.6 on 2024-02-24 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
        ('schedules', '0011_alter_schedule_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_empty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='daykind',
            field=models.ForeignKey(help_text="Fanni har hafta, toq, juft, bo'sh qoldirish. POST qilish uchun ID sini yuborish kerak", on_delete=django.db.models.deletion.CASCADE, to='schedules.daykind'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson_order',
            field=models.PositiveIntegerField(blank=True, help_text='yuborish kerak emas', null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson_type',
            field=models.CharField(blank=True, help_text='string', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.CharField(blank=True, help_text='string', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.CharField(blank=True, help_text="Har hafta, Toq hafta, Juft hafta uchun bu maydon majburiy. Bo'sh qoldirish uchun majburiy emas. string", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.CharField(blank=True, help_text='string', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(help_text='Telegram ID', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.ForeignKey(help_text='Hafta kunlari POST qilish uchun ID sini yuborish kerak', on_delete=django.db.models.deletion.CASCADE, to='schedules.weekday'),
        ),
    ]
